const area = ["Yerawda - Sangamwadi",
  "Kharadi Infotech Park",
  "Vimannagar Sanjay Park",
  "Nagpur Chawl",
  "Vishrantwadi Mhaske Vasti",
  "Bopodi Gaonthan",
  "Pune University",
  "Aundh ITI	",
  "Baner Balewadi",
  "Pashan Sutarwadi",
  "Janwadi-Gokhalenagar",
  "Model Colony",
  "Narveer Tanajiwadi	",
  "Deccan College",
  "Rajguru Road",
  "Subhashnagar",
  "Agakhan Palace",
  "Vadgaon Sheri",
  "Vadgaon Sheri - Ganesh Nagar",
  "Magarpatta City",
  "Koregaon Park",
  "Naidu Hospital",
  "Junabazaar Kumbharwada",
  "Balgandharva",
  "Wadarwadi-Pandavnagar",
  "MIT - Kelewadi",
  "Sutardara-Kishkindha Naga",
  "ARDE - Mhatobanagar",
  "Bavdhan Khurd",
  "Popularnagar Malwadi",
  "Shivane - Warje - Ramnagar",
  "Karvenagar - Gosavivasti",
  "Dahanukar Colony",
  "Gujrat Colony",
  "Deenanath Mangeshkar Hospital",
  "Kamla Nehru Park",
  "Shaniwarwada",
  "Kasba Peth",
  "KEM Hospital",
  "Collectorate",
  "Sopan Baug - Vikasnagar",
  "Lohiya Garden", "Vaiduwadi",
  "Sadhana Vidyalay",
  "Gliding Centre",
  "Mohammadwadi",
  "Wanavdi - Ramtekdi",
  "Arunkumar Vaidya Stadium",
  "Palkhi Vithoba Mandir",
  "Dr. Kotnis Hospital",
  "Mahatma Phule Mandai",
  "Tilak Smarak Mandir",
  "Vaikunth Smashanbhoomi",
  "PL Deshpande Udyan",
  "Suncity Wadgaon Budruk",
  "Janata Vasahat",
  "Sarasbaug Parvati",
  "Kadakmal Ali Hirabaug",
  "Mahatma Phule Smarak",
  "Kashewadi Gurunanaknagar",
  "Mahatma Phule Peth Kashewadi Bhawani Peth",
  "Kedar Vasti - Azadnagar",
  "Kondhwa Budruk", "Gokulnagar",
  "Bhagyodaynagar",
  "Salisbury Park",
  "Ghorpade Garden",
  "Adinath Society",
  "Aranyeshwar Taware Colony",
  "Sahakarnagar - Taljai",
  "Dhankawadi Padmavati",
  "Bibvewadi and KK Market",
  "Shivaji Market", "Gultekdi",
  "Upper Indiranagar",
  "Balajinagar Vaibhavnagar",
  "Bharati Vidyapeeth",
  "Katraj Dairy",
  "Katraj Maulinagar",
  "Lohegaon Airport"]
  export default area